__title__ = 'ds_tools'
__description__ = 'Misc Python 3 libraries and scripts'
__url__ = 'https://github.com/dskrypa/ds_tools'
__version__ = '2024.05.11-1'
__author__ = 'Doug Skrypa'
__author_email__ = 'dskrypa@gmail.com'
__copyright__ = 'Copyright 2024 Doug Skrypa'
